Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2024-05, with the labels that each got.

#534 Fix placeProperties is array of strings
  spec/processes.md
Labels: bug, documentation

#535 #449 Introduce postal address for person/company detail
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: refactoring

#532 #469
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: bug

#562 document layoutId in case of two deck vehicles (#547)
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: documentation

#559 address issues raised in #546
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: improvements
