Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2024-04, with the labels that each got.

#496 495 shouldnt ask for deprecated field in requestedinformation example
  spec/requested-information-examples.txt
  spec/requested-information-grammar.html
Labels: documentation

#497 491 improve oauth documentation on backend to backend oauth
  images/authentication/authentication_flow_be_to_be.png
  images/authentication/authentication_flow_be_to_be.puml
  spec/authentication.md
  spec/technical-principles.md
Labels: documentation, improvements

#500 495 more linking and examples
  spec/models.md
  spec/processes.md
Labels: documentation

#503 Update authentication.md
  spec/authentication.md
Labels: documentation

#502 Generalze PRESTIGE to PREMIUM
  spec/catalog-of-code-lists.md
Labels: improvements
