Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2024-02, with the labels that each got.

#338 Booking Split function
  specification/v3.0/OSDM-online-api-v3.0.2.yml
Labels: improvements

#457 Update OSDM-online-api-v3.2.0_draft.yml
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#458 408 need single soldproductid on offer parts
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#460 Update OSDM-online-api-v3.2.0_draft.yml
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: refactoring

#459 412 mapping back from bookingparts to offerparts 2
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#464 #454 Trips missing in ExchangeOperation
  specification/v3.2/OSDM-online-api-v3.2.0.yml
Labels: bug

#468 Update OSDM-online-api-v3.2.0.yml
  specification/v3.2/OSDM-online-api-v3.2.0.yml
Labels: improvements

#467 Update OSDM-online-api-v3.2.0.yml
  specification/v3.2/OSDM-online-api-v3.2.0.yml
Labels: improvements
