Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2024-01, with the labels that each got.

#421 reimboursementMethod
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#423 consumptions added in travel pass account
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#321 WIP: I-72.1 FulfillmentParts for Offer #320
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#429 Update OSDM-online-api-v3.2.0_draft.yml
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: documentation

#430 Update OSDM-online-api-v3.2.0_draft.yml
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: documentation

#428 412 mapping back from bookingparts to offerparts
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#422 fulfillment status moved
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: bug

#440 Fix typos and improve summaries
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements

#415 #411 Dual Approchaces documentation created
  _data/navigation.yml
  spec/dual-approaches.md
Labels: documentation

#433 passenger refs missing in fare
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: bug

#389 AccommodationType and AccommodationSubType items in openapi
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: documentation

#424 dscription added for description of applied passenger type
  specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
Labels: improvements
