Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2024-03, with the labels that each got.

#483 461 fulfillment media type app
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: refactoring

#484 Update OSDM-online-api-v3.3.0-draft.yml
  specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
Labels: improvements

#479 update of benerail sandbox
  tools/sandboxes.md
Labels: documentation

#488 Update BISTRO and add PRESTIGE as accommodation sub type
  spec/catalog-of-code-lists.md
Labels: documentation
