Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2025-03, with the labels that each got.

#886 feat: Support for coach deck layouts as presented in the OSDM tech workshops. Replaces coach layouts.
  specification/v3.5/OSDM-online-api-v3.5.0.yml
Labels: improvements

#908 More spell checking
  .vscode/settings.json
  specification/v3.5/OSDM-online-api-v3.5.0.yml
Labels: bug, documentation

#909 boolean type for passege between trains
  specification/v3.5/OSDM-online-api-v3.5.0.yml
Labels: improvements

#918 use code consistently in ServiceIconCode and GraphicElement
  specification/v3.5/OSDM-online-api-v3.5.0.yml
Labels: bug

#913 remove NotAcceptableResponse
  specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
Labels: bug

#932 926 add bookingcode and externalref to bookingsearchresult object in v3.6 and 4.0
  specification/v3.6/OSDM-online-api-v3.6.0.yml
  specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
Labels: improvements

#881 751 remove fulfillmentIds from exchangeOfferCollectionRequest
  specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
Labels: refactoring

#933 table of use cases for partial refund
  spec/after-sales-processes.md
Labels: documentation

#952 928 - description on provisional and confirmed prices in booking
  specification/v3.6/OSDM-online-api-v3.6.0.yml
Labels: documentation

#954 929 - use of booking part referenced in fulfillment
  specification/v3.6/OSDM-online-api-v3.6.0.yml
Labels: documentation

#953 928 - ballance replaced by the element names used in the api
  spec/processes.md
Labels: documentation
