Repository UnionInternationalCheminsdeFer/OSDM, pull requests merged in 2025-02, with the labels that each got.

#884 Typo in 3.5.0 CurrencyConversion
  specification/v3.5/OSDM-online-api-v3.5.0.yml
Labels: bug

#885 Update models.md
  spec/models.md
Labels: documentation

#853 816 Update preference group documentation
  spec/catalog-of-code-lists.md
Labels: documentation

#875 855 data type for time values in osdm offline
  specification/v4.0/ERA_Technical Document_TAP_B_13-offline-model-v4.0.0-draft.json
Labels: improvements

#864 820 products service get products by producttags
  specification/v3.5/OSDM-online-api-v3.5.0.yml
  specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
Labels: improvements

#878 split after sale documentation in a dedicate file
  _data/navigation.yml
  spec/after-sales-processes.md
  spec/processes.md
Labels: documentation

#889 874 overrule cleanup
  specification/v3.5/OSDM-online-api-v3.5.0.yml
  specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
Labels: refactoring
